project3 - beta/bookproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignUpView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
]


project3 - beta/bookproject/book/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index_view, name = 'index'),
    path('book/', views.ListBookView.as_view(), name = 'list-book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name = 'detail-book'),
    path('book/create/', views.CreateBookView.as_view(), name = 'create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name = 'delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name = 'update-book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name = 'review'),
    path('book/question/', views.CreateQuestionView.as_view(), name = 'question'),
    path('add-to-favorites/<int:book_id>/', views.add_to_favorites, name='add-to-favorites'),
    path('add-to-haveread/<int:book_id>/', views.add_to_havereadbooks, name='add-to-havereadbooks'),
    path('mypage/', views.mypage, name='mypage'),
    path('book/review/<int:review_id>/like', views.add_likes, name = 'add-likes'),
    path('book/howtouse/', views.HowToUse.as_view(), name = 'howtouse'),
]

project3 - beta/bookproject/bookproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #mediaファイルを使うための設定

project3 - beta/bookproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}{% endblock title%}技術書探し</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz4fnFO9gybU5i3r5c5zKj1FVhBHG9H9uli1kIBKf0BEVPWU4fFgPC4sap" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-wEmeIV1mKuiNpK+Knr6jY2oHnU9zfw5t3eGm4y3RXDvoYh5STmUh1Bmv0e4l6c9" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMmfUaxzTh1HrKucWRmC4ilnKIGLq9VtqIvb6wW" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class = "navbar navbar-dark sticky-top bg-primary" >
        <div class="navbar-nav d-flex flex-row">
            <a class="navbar-brand icontext" href="#">We Tech Shelf</a>
            
            <a class="nav-link mx-3 highlight-text" href="{% url 'index' %}">HOME</a>
            <a class="nav-link mx-3 highlight-text" href="{% url 'list-book' %}">技術書一覧</a>
            <a class="nav-link mx-3 highlight-text" href="{% url 'create-book' %}">技術書追加</a>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Others
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'mypage' %}">My Page</a></li>
                  <li><a class="dropdown-item" href="{% url 'howtouse' %}">使い方</a></li>
                  <li><a class="dropdown-item" href="{% url 'question'%}">お問い合わせ</a></li>
                </ul>
            </div>
        </div>
        <div class="navbar-nav d-flex flex-row">
            {% if request.user.is_authenticated %}
            <a class = "nav-link mx-3 highlight-text" href="{% url 'accounts:logout' %}">ログアウト</a>
            {% else %}
            <a class="nav-link mx-3 highlight-text" href="{% url 'accounts:login' %}">ログイン</a>
            <a class="nav-link mx-3 highlight-text" href="{% url 'accounts:signup' %}">会員登録</a>
            {% endif %}
        </div>
    </nav>
    <div class ="p-4">
        <h1>{% block h1%}{% endblock%}</h1>


         {% block content %}
        {% endblock content %}
    </div>
    <div class="footer">
        <div class="ego">
            <a class="git" href="https://github.com/DeliveRy1987">Git Hub</a>
            <p>© 2045 WE shelf</p>
        </div>    
    </div>
    
</body>
</html>